export type QuickfireSentence = {
  japanese: string;
  english: string;
  needs: string[];
};

export const vocabularyEnglish: Record<string, string> = {
  "すみません":"excuse me / sorry",
  "いま":"now",
  "まい日":"every day",
  "はやく":"early",
  "あびます":"take a shower",
  "おきます":"get up",
  "おわります":"finish",
  "かえります":"go home",
  "ねます":"go to bed",
  "のみます":"drink",
  "はいります":"enter / get in",
  "(お)ふろ":"bath",
  "ぶかつ":"club activities",
  "しゅくだい":"homework",
  "うち":"home",
  "学校":"school",
  "コンビニ":"convenience store",
  "ばいてん":"canteen / tuck shop",
  "(お)ちゃ":"tea",
  "ヨーグルト":"yoghurt",
  "カレーライス":"curry rice",
  "(あさ)ごはん":"breakfast",
  "(お)べんとう":"packed lunch",
  "ばんごはん":"dinner",
  "(お)ひるごはん":"lunch",
  "きゅうしょく":"school lunch",

  "小学校":"primary school",
  "中学校":"junior high school",
  "高校":"senior high school",
  "大学":"university",
  "(お)ひるやすみ":"lunch break",
  "そうじ":"cleaning",
  "かもく":"school subject",
  "えいご":"English",
  "こくご":"Japanese language",
  "すう学":"mathematics",
  "おんがく":"music",
  "りか":"science",
  "たいいく":"physical education",
  "ぎじゅつ":"technology",
  "かてい":"home economics",
  "どうとく":"moral education",
  "れきし":"history",
  "ちり":"geography",
  "自己紹介":"self-introduction",
  "つまらない":"boring",
  "にがて(な)":"not good at",
  "むずかしい":"difficult",
  "きょう":"today",

  "はる（春）":"spring",
  "なつ（夏）":"summer",
  "あき（秋）":"autumn",
  "ふゆ（冬）":"winter",
  "一がつ":"January",
  "二がつ":"February",
  "三がつ":"March",
  "にゅう学しき":"entrance ceremony",
  "えんそく":"excursion",
  "水えいたいかい":"swimming carnival",
  "やすみ":"holiday / break",
  "はるやすみ":"spring holiday",
  "なつやすみ":"summer holiday",
  "ふゆやすみ":"winter holiday",
  "りんぎょうさい":"forestry festival",
  "ぶんかさい":"cultural festival",
  "しゅう学りょこう":"school trip",
  "ミュージカル":"musical",
  "えんげき":"play / drama",
  "ひこうき":"aeroplane",
  "くるま":"car",
  "じてんしゃ":"bicycle",
  "しんかんせん":"bullet train",
  "スクールバス":"school bus",
  "タクシー":"taxi",
  "でんしゃ":"train",
  "バス":"bus",
  "あるいて":"on foot",

  "しゅみ":"hobby",
  "りょうり":"cooking",
  "どくしょ":"reading",
  "つり":"fishing",
  "へや":"room",
  "うみ":"sea",
  "ビーチ":"beach",
  "山":"mountain",
  "川":"river",
  "天気":"weather",
  "くもり":"cloudy",
  "つくります":"make",
  "ひきます":"play an instrument",
  "(で)あそびます":"play",
  "しゃしんをとります":"take photos",
  "かきます":"write / draw",
  "つかいます":"use",
  "さんぽします":"take a walk",
  "うたいます":"sing",
  "あした":"tomorrow",
  "あさ":"morning",
  "きょ年":"last year",
  "たくさん":"a lot",
  "かいもの":"shopping",
  "アクションえいが":"action film",
  "おべんとう":"packed lunch",
  "やすみます":"rest",
  "大好き":"love / really like",
  "好き":"like",
  "あまり好きじゃない":"do not like very much",

  "あし":"leg / foot",
  "あたま":"head",
  "かお":"face",
  "かみ(の毛)":"hair",
  "くち":"mouth",
  "しっぽ":"tail",
  "せ":"height",
  "手":"hand",
  "はな":"nose",
  "耳":"ear",
  "目":"eye",
  "アニメ":"anime",
  "キャラクター":"character",
  "コスプレ":"cosplay",
  "ふく":"clothes",
  "サービス":"service",
  "ながい":"long",
  "みじかい":"short",
  "たかい":"tall / high",
  "ひくい":"short / low",
  "つよい":"strong",
  "すてき(な)":"lovely",
  "へん(な)":"strange",
  "いろいろ(な)":"various",
  "きます":"wear",
  "できます":"can do",
  "先しゅう":"last week",
  "まい年":"every year",

  "おとこの人":"man",
  "おんなの人":"woman",
  "パーティー":"party",
  "プレゼント":"present",
  "ギフトカード":"gift card",
  "カラオケ":"karaoke",
  "よる":"evening / night",
  "わたあめ":"fairy floss",
  "たこやき":"takoyaki",
  "とうもろこし":"corn",
  "やきそば":"yakisoba",
  "きもの":"kimono",
  "ゆかた":"yukata",
  "はっぴ":"happi coat",
  "おめん":"mask",
  "はなび":"fireworks",
  "めずらしい":"unusual / rare",
  "つめたい":"cold to the touch",
  "たいせつ(な)":"important",
  "もっと":"more",
  "また":"again",

  "人気があります":"is popular",
  "ウェルネス":"wellness",
  "けんこう":"health",
  "ストレス":"stress",
  "エネルギー":"energy",
  "自然":"nature",
  "ヨガ":"yoga",
  "めいそう":"meditation",
  "にわ":"garden",
  "りょかん":"traditional Japanese inn",
  "せんそう":"war",
  "しんりんよく":"forest bathing",
  "いなか":"countryside",
  "さいがい":"disaster",
  "ツーリズム":"tourism",
  "へらします":"reduce",
  "上げます":"raise / increase",
  "リラックスします":"relax",
  "ゆっくりする":"take it easy",
  "かんこうする":"go sightseeing",

  "広島":"Hiroshima",
  "ツアー":"tour",
  "ホテル":"hotel",
  "部屋":"room",
  "洋室":"Western-style room",
  "平和記念公園":"Peace Memorial Park",
  "地元":"local area / local",
  "伝統工芸":"traditional crafts",
  "店":"shop",
  "オーストラリア":"Australia",
  "フェリー":"ferry",
  "宮島":"Miyajima",
  "神社":"Shinto shrine",
  "旅行":"trip / travel",
  "世界遺産":"World Heritage Site",
  "メール":"email",
  "家族":"family",
  "タオル":"towel",
  "シーツ":"sheets",
  "観光客":"tourist",
  "経験":"experience",
  "ガイド":"guide",
  "歴史":"history",
  "平和":"peace",
  "晩ご飯":"dinner",
  "お好み焼き":"okonomiyaki",
  "筆":"calligraphy brush",
  "書道":"Japanese calligraphy",
  "写真":"photo",
  "教えます":"tell / teach",
  "着きます":"arrive",
  "観光します":"go sightseeing",
  "説明します":"explain",
  "話します":"talk / speak",
  "食べます":"eat",
  "買います":"buy",
  "帰ります":"return / go home",
  "始めます":"begin",
  "乗ります":"ride / board",
  "知ります":"know / learn",
  "撮ります":"take (a photo)",
  "会います":"meet",
  "広い":"spacious / wide",
  "きれい":"clean / beautiful",
  "新しい":"new",
  "気もちがいい":"feels pleasant",
  "多い":"many",
  "こんでいます":"is crowded",
  "親切(な)":"kind / helpful",
  "有名(な)":"famous",
  "楽しみ(な)":"looking forward to",
  "きのう":"yesterday",
  "午後":"afternoon",
  "二日間":"for two days",
  "今日":"today",
  "午前中":"morning / before noon",
  "明日":"tomorrow",
  "来月":"next month",
  "ありがとう":"thank you",
  "〜てくれます":"does something for me/us",
  "〜予定です":"plan to / be scheduled to",
  "〜つもりです":"intend to",
  "〜たいと思っています":"am thinking of wanting to",
  "〜について":"about / concerning",
  "〜そうです":"I hear that / apparently",
  "〜たら":"when / after",
  "〜間に":"while / during",
};

export const quickfireSentenceBank: Record<string, QuickfireSentence[]> = {
  "iitomo2-ch1":[
    {japanese:"まい日、はやくおきます。",english:"I get up early every day.",needs:["まい日","はやく","おきます"]},
    {japanese:"おちゃをのみます。",english:"I drink tea.",needs:["(お)ちゃ","のみます"]},
    {japanese:"学校からうちにかえります。",english:"I go home from school.",needs:["学校","うち","かえります"]},
    {japanese:"ぶかつがおわります。",english:"Club activities finish.",needs:["ぶかつ","おわります"]},
    {japanese:"ばんごはんのあと、おふろにはいります。",english:"After dinner, I take a bath.",needs:["ばんごはん","(お)ふろ","はいります"]},
    {japanese:"しゅくだいのあと、ねます。",english:"After homework, I go to bed.",needs:["しゅくだい","ねます"]},
  ],
  "iitomo2-ch2":[
    {japanese:"すう学はむずかしいです。",english:"Mathematics is difficult.",needs:["すう学","むずかしい"]},
    {japanese:"おんがくは好きなかもくです。",english:"Music is my favourite subject.",needs:["おんがく","かもく","好きなかもく"]},
    {japanese:"きょう、そうじをします。",english:"Today, I do the cleaning.",needs:["きょう","そうじ","そうじ(を)します"]},
    {japanese:"たいいくはにがてです。",english:"I am not good at physical education.",needs:["たいいく","にがて(な)"]},
    {japanese:"高校は三時までです。",english:"Senior high school finishes at three o'clock.",needs:["高校","まで"]},
    {japanese:"れきしはつまらないです。",english:"History is boring.",needs:["れきし","つまらない"]},
  ],
  "iitomo2-ch3":[
    {japanese:"えんそくにバスで行きます。",english:"I go on the excursion by bus.",needs:["えんそく","バス"]},
    {japanese:"なつやすみにひこうきで行きます。",english:"I travel by aeroplane during the summer holiday.",needs:["なつやすみ","ひこうき"]},
    {japanese:"ぶんかさいでミュージカルをみます。",english:"I watch a musical at the cultural festival.",needs:["ぶんかさい","ミュージカル"]},
    {japanese:"しゅう学りょこうにしんかんせんで行きます。",english:"I go on the school trip by bullet train.",needs:["しゅう学りょこう","しんかんせん"]},
    {japanese:"はるににゅう学しきがあります。",english:"The entrance ceremony is in spring.",needs:["はる（春）","にゅう学しき"]},
    {japanese:"ふゆやすみにでんしゃで行きます。",english:"I travel by train during the winter holiday.",needs:["ふゆやすみ","でんしゃ"]},
  ],
  "iitomo2-ch4":[
    {japanese:"しゅうまつにりょうりをします。",english:"I cook on the weekend.",needs:["しゅうまつに","りょうり"]},
    {japanese:"うみでしゃしんをとります。",english:"I take photos at the sea.",needs:["うみ","しゃしんをとります"]},
    {japanese:"ひまな時にどくしょをします。",english:"I read in my free time.",needs:["ひまな時に","どくしょ"]},
    {japanese:"山でさんぽします。",english:"I take a walk in the mountains.",needs:["山","さんぽします"]},
    {japanese:"あした、へやでうたいます。",english:"Tomorrow, I will sing in my room.",needs:["あした","へや","うたいます"]},
    {japanese:"ビーチでたくさんしゃしんをとります。",english:"I take lots of photos at the beach.",needs:["ビーチ","たくさん","しゃしんをとります"]},
    {japanese:"つりが大好きです。",english:"I love fishing.",needs:["つり","大好き"]},
    {japanese:"アクションえいがは好きです。",english:"I like action films.",needs:["アクションえいが","好き"]},
    {japanese:"かいものはあまり好きじゃないです。",english:"I do not like shopping very much.",needs:["かいもの","あまり好きじゃない"]},
    {japanese:"あした、やすみます。",english:"I will rest tomorrow.",needs:["あした","やすみます"]},
    {japanese:"おべんとうをつくります。",english:"I make a packed lunch.",needs:["おべんとう","つくります"]},
  ],
  "iitomo2-ch5":[
    {japanese:"このキャラクターはせがたかいです。",english:"This character is tall.",needs:["キャラクター","せがたかい"]},
    {japanese:"このキャラクターはかみの毛がながいです。",english:"This character has long hair.",needs:["キャラクター","かみ(の毛)","ながい"]},
    {japanese:"このキャラクターはしっぽがみじかいです。",english:"This character has a short tail.",needs:["キャラクター","しっぽ","みじかい"]},
    {japanese:"このキャラクターはつよいです。",english:"This character is strong.",needs:["キャラクター","つよい"]},
    {japanese:"先しゅう、コスプレのふくをきました。",english:"Last week, I wore cosplay clothes.",needs:["先しゅう","コスプレ","ふく","きます"]},
    {japanese:"まい年、アニメのコスプレをします。",english:"Every year, I do anime cosplay.",needs:["まい年","アニメ","コスプレ"]},
  ],
  "iitomo2-ch6":[
    {japanese:"はなびはたのしかったです。",english:"The fireworks were fun.",needs:["はなび","たのしかったです"]},
    {japanese:"たこやきはおいしかったです。",english:"The takoyaki was delicious.",needs:["たこやき","おいしかったです"]},
    {japanese:"みんなでおいわいします。",english:"We celebrate together.",needs:["みんなで","(お)いわいします"]},
    {japanese:"パーティーはこんでいました。",english:"The party was crowded.",needs:["パーティー","こんでいました"]},
    {japanese:"プレゼントをもらいます。",english:"I receive a present.",needs:["プレゼント","もらいます"]},
    {japanese:"ゆかたはたいせつです。",english:"The yukata is important.",needs:["ゆかた","たいせつ(な)"]},
  ],
  "iitomo2-tourism":[
    {japanese:"ホテルは人気があります。",english:"The hotel is popular.",needs:["ホテル","人気があります"]},
    {japanese:"しんりんよくでストレスをへらします。",english:"I reduce stress through forest bathing.",needs:["しんりんよく","ストレス","へらします"]},
    {japanese:"ヨガでエネルギーを上げます。",english:"I increase my energy with yoga.",needs:["ヨガ","エネルギー","上げます"]},
    {japanese:"いなかでゆっくりします。",english:"I take it easy in the countryside.",needs:["いなか","ゆっくりする"]},
    {japanese:"自然の中でリラックスします。",english:"I relax in nature.",needs:["自然","リラックスします"]},
    {japanese:"りょかんのにわでめいそうします。",english:"I meditate in the ryokan garden.",needs:["りょかん","にわ","めいそう"]},
  ],
  "year11-hiroshima":[
    {japanese:"きのうの午後、家族と広島に着きました。",english:"Yesterday afternoon, I arrived in Hiroshima with my family.",needs:["きのう","午後","家族","広島","着きます"]},
    {japanese:"広島で二日間、観光する予定です。",english:"I plan to sightsee in Hiroshima for two days.",needs:["広島","二日間","観光します","〜予定です"]},
    {japanese:"今日の午前中、平和記念公園に行きました。",english:"This morning, I went to Peace Memorial Park.",needs:["今日","午前中","平和記念公園"]},
    {japanese:"ガイドは広島の歴史について説明しました。",english:"The guide explained Hiroshima's history.",needs:["ガイド","広島","歴史","〜について","説明します"]},
    {japanese:"晩ご飯に地元のお好み焼きを食べるつもりです。",english:"I intend to eat local okonomiyaki for dinner.",needs:["晩ご飯","地元","お好み焼き","食べます","〜つもりです"]},
    {japanese:"伝統工芸の店で筆を買いたいと思っています。",english:"I am thinking of buying a brush at a traditional craft shop.",needs:["伝統工芸","店","筆","買います","〜たいと思っています"]},
    {japanese:"明日はフェリーに乗って宮島に行く予定です。",english:"Tomorrow I plan to take a ferry to Miyajima.",needs:["明日","フェリー","乗ります","宮島","〜予定です"]},
    {japanese:"この神社は世界遺産だそうです。",english:"I hear that this shrine is a World Heritage Site.",needs:["神社","世界遺産","〜そうです"]},
  ],
};

export const cleanJapaneseWord = (value: string) => value
  .replace(/^\(お\)/, "お")
  .replace(/^\(あさ\)/, "あさ")
  .replace(/^\(で\)/, "")
  .replace(/\(な\)/g, "")
  .replace(/かみ\(の毛\)/g, "かみの毛")
  .replace(/（([^）]+)）/g, "（$1）");
