export type QuickfireSentence = {
  japanese: string;
  english: string;
  needs: string[];
};

export const vocabularyEnglish: Record<string, string> = {
  "すみません":"excuse me / sorry",
  "いま":"now",
  "まい日":"every day",
  "はやく":"early",
  "あびます":"take a shower",
  "おきます":"get up",
  "おわります":"finish",
  "かえります":"go home",
  "ねます":"go to bed",
  "のみます":"drink",
  "はいります":"enter / get in",
  "(お)ふろ":"bath",
  "ぶかつ":"club activities",
  "しゅくだい":"homework",
  "うち":"home",
  "学校":"school",
  "コンビニ":"convenience store",
  "(お)てん":"shop",
  "(お)ちゃ":"tea",
  "ヨーグルト":"yoghurt",
  "カレーライス":"curry rice",
  "(あさ)ごはん":"breakfast",
  "(お)べんとう":"packed lunch",
  "ばんごはん":"dinner",
  "(お)ひるごはん":"lunch",
  "きゅうしょく":"school lunch",

  "小学校":"primary school",
  "中学校":"junior high school",
  "高校":"senior high school",
  "大学":"university",
  "(お)ひるやすみ":"lunch break",
  "そうじ":"cleaning",
  "かもく":"school subject",
  "えいご":"English",
  "こくご":"Japanese language",
  "すう学":"mathematics",
  "おんがく":"music",
  "りか":"science",
  "たいいく":"physical education",
  "ぎじゅつ":"technology",
  "かてい":"home economics",
  "どうとく":"moral education",
  "れきし":"history",
  "ちり":"geography",
  "自己紹介":"self-introduction",
  "つまらない":"boring",
  "にがて(な)":"not good at",
  "むずかしい":"difficult",
  "きょう":"today",

  "はる（春）":"spring",
  "なつ（夏）":"summer",
  "あき（秋）":"autumn",
  "ふゆ（冬）":"winter",
  "一がつ":"January",
  "二がつ":"February",
  "三がつ":"March",
  "にゅう学しき":"entrance ceremony",
  "えんそく":"excursion",
  "水えいたいかい":"swimming carnival",
  "やすみ":"holiday / break",
  "はるやすみ":"spring holiday",
  "なつやすみ":"summer holiday",
  "ふゆやすみ":"winter holiday",
  "りんぎょうさい":"forestry festival",
  "ぶんかさい":"cultural festival",
  "しゅう学りょこう":"school trip",
  "ミュージカル":"musical",
  "えんげき":"play / drama",
  "ひこうき":"aeroplane",
  "くるま":"car",
  "じてんしゃ":"bicycle",
  "しんかんせん":"bullet train",
  "スクールバス":"school bus",
  "タクシー":"taxi",
  "でんしゃ":"train",
  "バス":"bus",
  "あるいて":"on foot",

  "しゅみ":"hobby",
  "りょうり":"cooking",
  "どくしょ":"reading",
  "つり":"fishing",
  "へや":"room",
  "うみ":"sea",
  "ビーチ":"beach",
  "山":"mountain",
  "川":"river",
  "天気":"weather",
  "くもり":"cloudy",
  "つくります":"make",
  "ひきます":"play an instrument",
  "(で)あそびます":"play",
  "しゃしんをとります":"take photos",
  "かきます":"write / draw",
  "つかいます":"use",
  "さんぽします":"take a walk",
  "うたいます":"sing",
  "あした":"tomorrow",
  "あさ":"morning",
  "きょ年":"last year",
  "たくさん":"a lot",

  "あし":"leg / foot",
  "あたま":"head",
  "かお":"face",
  "かみ(の毛)":"hair",
  "くち":"mouth",
  "しっぽ":"tail",
  "せ":"height",
  "手":"hand",
  "はな":"nose",
  "耳":"ear",
  "目":"eye",
  "アニメ":"anime",
  "キャラクター":"character",
  "コスプレ":"cosplay",
  "ふく":"clothes",
  "サービス":"service",
  "ながい":"long",
  "みじかい":"short",
  "たかい":"tall / high",
  "ひくい":"short / low",
  "つよい":"strong",
  "すてき(な)":"lovely",
  "へん(な)":"strange",
  "いろいろ(な)":"various",
  "きます":"wear",
  "できます":"can do",
  "先しゅう":"last week",
  "まい年":"every year",

  "おとこの人":"man",
  "おんなの人":"woman",
  "パーティー":"party",
  "プレゼント":"present",
  "ギフトカード":"gift card",
  "カラオケ":"karaoke",
  "よる":"evening / night",
  "わたあめ":"fairy floss",
  "たこやき":"takoyaki",
  "とうもろこし":"corn",
  "やきそば":"yakisoba",
  "きもの":"kimono",
  "ゆかた":"yukata",
  "はっぴ":"happi coat",
  "おめん":"mask",
  "はなび":"fireworks",
  "めずらしい":"unusual / rare",
  "つめたい":"cold to the touch",
  "たいせつ(な)":"important",
  "もっと":"more",
  "また":"again",
};

export const quickfireSentenceBank: Record<string, QuickfireSentence[]> = {
  "iitomo2-ch1":[
    {japanese:"まい日、はやくおきます。",english:"I get up early every day.",needs:["まい日","はやく","おきます"]},
    {japanese:"おちゃをのみます。",english:"I drink tea.",needs:["(お)ちゃ","のみます"]},
    {japanese:"学校からうちにかえります。",english:"I go home from school.",needs:["学校","うち","かえります"]},
    {japanese:"ぶかつがおわります。",english:"Club activities finish.",needs:["ぶかつ","おわります"]},
    {japanese:"ばんごはんのあと、おふろにはいります。",english:"After dinner, I take a bath.",needs:["ばんごはん","(お)ふろ","はいります"]},
    {japanese:"しゅくだいのあと、ねます。",english:"After homework, I go to bed.",needs:["しゅくだい","ねます"]},
  ],
  "iitomo2-ch2":[
    {japanese:"すう学はむずかしいです。",english:"Mathematics is difficult.",needs:["すう学","むずかしい"]},
    {japanese:"おんがくは好きなかもくです。",english:"Music is my favourite subject.",needs:["おんがく","かもく","好きなかもく"]},
    {japanese:"きょう、そうじをします。",english:"Today, I do the cleaning.",needs:["きょう","そうじ","そうじ(を)します"]},
    {japanese:"たいいくはにがてです。",english:"I am not good at physical education.",needs:["たいいく","にがて(な)"]},
    {japanese:"高校は三時までです。",english:"Senior high school finishes at three o'clock.",needs:["高校","まで"]},
    {japanese:"れきしはつまらないです。",english:"History is boring.",needs:["れきし","つまらない"]},
  ],
  "iitomo2-ch3":[
    {japanese:"えんそくにバスで行きます。",english:"I go on the excursion by bus.",needs:["えんそく","バス"]},
    {japanese:"なつやすみにひこうきで行きます。",english:"I travel by aeroplane during the summer holiday.",needs:["なつやすみ","ひこうき"]},
    {japanese:"ぶんかさいでミュージカルをみます。",english:"I watch a musical at the cultural festival.",needs:["ぶんかさい","ミュージカル"]},
    {japanese:"しゅう学りょこうにしんかんせんで行きます。",english:"I go on the school trip by bullet train.",needs:["しゅう学りょこう","しんかんせん"]},
    {japanese:"はるににゅう学しきがあります。",english:"The entrance ceremony is in spring.",needs:["はる（春）","にゅう学しき"]},
    {japanese:"ふゆやすみにでんしゃで行きます。",english:"I travel by train during the winter holiday.",needs:["ふゆやすみ","でんしゃ"]},
  ],
  "iitomo2-ch4":[
    {japanese:"しゅうまつにりょうりをします。",english:"I cook on the weekend.",needs:["しゅうまつに","りょうり"]},
    {japanese:"うみでしゃしんをとります。",english:"I take photos at the sea.",needs:["うみ","しゃしんをとります"]},
    {japanese:"ひまな時にどくしょをします。",english:"I read in my free time.",needs:["ひまな時に","どくしょ"]},
    {japanese:"山でさんぽします。",english:"I take a walk in the mountains.",needs:["山","さんぽします"]},
    {japanese:"あした、へやでうたいます。",english:"Tomorrow, I will sing in my room.",needs:["あした","へや","うたいます"]},
    {japanese:"ビーチでたくさんしゃしんをとります。",english:"I take lots of photos at the beach.",needs:["ビーチ","たくさん","しゃしんをとります"]},
  ],
  "iitomo2-ch5":[
    {japanese:"このキャラクターはせがたかいです。",english:"This character is tall.",needs:["キャラクター","せがたかい"]},
    {japanese:"このキャラクターはかみの毛がながいです。",english:"This character has long hair.",needs:["キャラクター","かみ(の毛)","ながい"]},
    {japanese:"このキャラクターはしっぽがみじかいです。",english:"This character has a short tail.",needs:["キャラクター","しっぽ","みじかい"]},
    {japanese:"このキャラクターはつよいです。",english:"This character is strong.",needs:["キャラクター","つよい"]},
    {japanese:"先しゅう、コスプレのふくをきました。",english:"Last week, I wore cosplay clothes.",needs:["先しゅう","コスプレ","ふく","きます"]},
    {japanese:"まい年、アニメのコスプレをします。",english:"Every year, I do anime cosplay.",needs:["まい年","アニメ","コスプレ"]},
  ],
  "iitomo2-ch6":[
    {japanese:"はなびはたのしかったです。",english:"The fireworks were fun.",needs:["はなび","たのしかったです"]},
    {japanese:"たこやきはおいしかったです。",english:"The takoyaki was delicious.",needs:["たこやき","おいしかったです"]},
    {japanese:"みんなでおいわいします。",english:"We celebrate together.",needs:["みんなで","(お)いわいします"]},
    {japanese:"パーティーはこんでいました。",english:"The party was crowded.",needs:["パーティー","こんでいました"]},
    {japanese:"プレゼントをもらいます。",english:"I receive a present.",needs:["プレゼント","もらいます"]},
    {japanese:"ゆかたはたいせつです。",english:"The yukata is important.",needs:["ゆかた","たいせつ(な)"]},
  ],
};

export const cleanJapaneseWord = (value: string) => value
  .replace(/^\(お\)/, "お")
  .replace(/^\(あさ\)/, "あさ")
  .replace(/^\(で\)/, "")
  .replace(/\(な\)/g, "")
  .replace(/かみ\(の毛\)/g, "かみの毛")
  .replace(/（([^）]+)）/g, "（$1）");
